# Donk co Service Fab

- type: latheRecipe
  parent: DrinkDisposableCup
  id: DrinkDonkcoCup
  result: DrinkDonkcoCup
  name: Donk co Disposable Cup

- type: latheRecipe
  parent: NFBaseBoxRecipe
  id: FoodBoxDonkngo
  result: FoodBoxDonkngo
  name: Donk n Go Box

    - type: latheRecipe
      parent: NFBaseJumpsuitRecipe
      id: ClothingUniformJumpsuitDonkcoChef
      result: ClothingUniformJumpsuitDonkcoChef

    - type: latheRecipe
      parent: NFBaseCoatRecipe
      id: ClothingOuterDonkcoApron
      result: ClothingOuterDonkcoApron

    - type: latheRecipe
      parent: NFBaseHatRecipe
      id: ClothingHeadHatDonkcoHat
      result: ClothingHeadHatDonkcoHat
