- type: flarpiSettings
  id: FlarpiSettings_Default
  pointsPerFlarpi: 1000
  flarpiName: freelancer
  baseFlarpi: 5
  nearbyRadius: 25
  freelancerCountMode: Nearby
  freelancerCalcMode: Doubling
  freelancerMaxCount: 4
  nfsdCountMode: Nope
  nfsdCalcMode: Nope

- type: flarpiSettings
  id: FlarpiSettings_NFSD
  pointsPerFlarpi: 1000
  flarpiName: nfsd
  baseFlarpi: 5
  nearbyRadius: 25
  freelancerCalcMode: Linear
  freelancerCountMode: Online
  freelancerMaxCount: 5
  nfsdCalcMode: Linear
  nfsdCountMode: Online

