- type: entity
  parent: [BaseC1Contraband, AccessConfigurator]
  id: AccessConfiguratorCivilian
  name: civilian access configurator
  description: An access configurator commonly used by ship captains, intended for the general market in the frontier.
  components:
  - type: Sprite
    sprite: _CS/Objects/Tools/civilian_access_configurator.rsi
  - type: Clothing
    sprite: _CS/Objects/Tools/civilian_access_configurator.rsi
  - type: AccessOverrider
    accessLevels:
      - Engineering
      - External
      - Frontier
      - Janitor
      - Mail
      - Maintenance
      - Medical
      - Security
      - Service
  - type: StaticPrice
    price: 500
    vendPrice: 2500
